### ISSUE TITLE
Context provided to NewSigner isn't passed along to Sign operations

### ISSUE THREAD

**Issue by josephlr** [sethvargo/go-gcpkms#5]
I initially expected the `ctx` passed to `NewSigner` to be the default for subsequent operations, and for it only to change if overridden by `WithContext`. However, it looks like the code defaults to `context.Background` even if you pass a non-backgroud context in the constructor.

Would it be reasonable to pass along the context from the constructor?

**Comment by sethvargo** [comment]
The context to `NewSigner` is just the context used to setup the signer, since we need to download the public key from Cloud KMS. You can add a context to an individual sign request with `WithContext`:

```
s, err := signer.NewSigner(ctx, client, "projects/...")
if err != nil {
  // ...
}

newCtx := context.WithTimeout(5*time.Minute)
s = s.WithContext(newCtx)
```

It's usually frowned upon to "store" a context from a call without explicitly making it clear that that's the behavior (hence the separate WithContext method).

**Comment by josephlr** [comment]
Thanks! That makes sense. It also seems reasonable that a user might use different contexts for these two senarios
